/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'aishwaryav' at '6/29/16 11:07 AM' with Gradle 2.14
 *
 * @author aishwaryav, @date 6/29/16 11:07 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
